#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := espnow_datalogger_basestation

include $(IDF_PATH)/make/project.mk

